name: manager-scorecard-bot

on:
  schedule:
    - cron: '0 14 * * *' # runs at 14:00 UTC (9am Central) everyday
    
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning' 
        type: choice
        options:
        - info
        - warning
        - debug 
      tags:
        description: 'Test scenario tags'
        required: false 
        type: boolean
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true 

          
jobs:

  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.DANI_GH_TOKEN }}
      TWITTERACCESSTOKEN: ${{ secrets.TWITTERACCESSTOKEN }}
      TWITTERACCESSTOKENSECRET: ${{ secrets.TWITTERACCESSTOKENSECRET }}
      TWITTERAPIKEY: ${{ secrets.TWITTERAPIKEY }}
      TWITTERAPISECRET: ${{ secrets.TWITTERAPISECRET }}
    steps:

      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: 4.2.3
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true
          
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          cache-version: 1
          extra-packages: |
            rvest
            tidyverse
            gt
            baseballr
            lubridate
            slider
            randomForest
            piggyback
            padr

      - name: Run daily script
        run: Rscript -e 'source("02-get_daily_results.R")'
          

        
